# Generated by Django 4.0.5 on 2022-06-30 12:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название поста')),
                ('annotation', models.TextField(verbose_name='Краткий текст')),
                ('body', models.TextField(verbose_name='Полный текст')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 6, 30, 12, 10, 9, 333238, tzinfo=utc), verbose_name='Дата создания')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикация',
                'ordering': ['created_at'],
            },
        ),
    ]
